lin_guestbook:
    type: rest
    prefix: /
    resource: "@LinGuestbookBundle/Resources/config/routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc